include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - avoid_unused_constructor_parameters
    - prefer_final_locals
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_if_null_operators
    - unnecessary_null_comparison
    - prefer_const_constructors_in_immutables

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - .dart_tool/**
    - "**.g.dart"
    - "**.freezed.dart"
