name: digm_app
description: A decentralized music platform powered by Fuego.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.2.2
  audioplayers: ^6.0.0
  fuego_core:
    path: ../libfuego_core/ffi-bridge/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
